server:
  port: 8080

spring:
  application:
    name: pep_aston

  jpa.properties.hibernate:
    connection:
      url: jdbc:postgresql://localhost:40254/postgres
      username: admin
      password: qQ111111
      driver_class: org.postgresql.Driver
    default_schema: public
    hbm2ddl.auto: update                                      # update # validate
    show_sql: true   # Показывает SQL запросы в консоли         # true   # false
    format_sql: true # Показывает SQL запросы не в одну строчку # true   # false