server:
  port: 8080

spring:

  application:
    name: pep_aston


  datasource:
    url: jdbc:postgresql://localhost:40254/postgres
    username: admin
    password: qQ111111
    driver-class-name: org.postgresql.Driver

  jpa.properties.hibernate:
    connection:
      url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      driver_class: ${spring.datasource.driver-class-name}
    default_schema: public
    hbm2ddl.auto: update                                        # update # validate
    show_sql: false   # Показывает SQL запросы в консоли         # true   # false
    format_sql: false # Показывает SQL запросы не в одну строчку # true   # false